### ISSUE TITLE
是否考虑添加锁机制？

### ISSUE THREAD

**Issue by highmind** [uni-helper/uni-network#40]
### 对问题的清晰和简明的描述

是否考虑添加锁机制？在响应拦截器中，给未进入响应拦截器的请求加锁。用于在响应拦截器中，刷新token。刷新token完成以后，重新请求为执行的请求
使用场景：一般用无感刷新token。

### 推荐的解决方案

可以参考flyio的方式

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
我担心这会使得这个项目难以同步 axios，同时将这个项目变成黑盒进而引出更多的问题。我希望可以先听听更多人的意见再做决定。

就目前而言，我认为无感刷新 token 可以结合 @tanstack/vue-query 等更强大的请求管理库来做，如果不希望使用请求管理库，我们可以在 README 中增加这方面的使用示例（欢迎 PR 👏）。

欢迎进一步讨论 🙏

**Comment by highmind** [comment]
如果在如何实现上有分歧，麻烦加一下相关示例，多谢！

**Comment by ModyQyW** [comment]
会尽快补充使用示例

**Comment by ModyQyW** [comment]
目前安排在下周更新文档，会增加该部分内容

**Comment by highmind** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wu ***@***.***&gt;; 
发送时间: 2023年10月31日(星期二) 下午3:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [uni-helper/uni-network] 是否考虑添加锁机制？ (Issue #40)





 
目前安排在下周更新文档，会增加该部分内容
