### ISSUE TITLE
小程序打包提示[vite]: Rollup failed to resolve import "statuses" from 

### ISSUE THREAD

**Issue by DMzmwh** [uni-helper/uni-network#43]
### 描述问题

`[vite]: Rollup failed to resolve import "statuses" from "D:/project/uniapp小程序-配套资料/03-code/uni-shop/node_modules/@uni-helper/uni-network/dist/index.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external``

### 复现

1

### 系统信息

```Shell
Need to install the following packages:
  envinfo@7.11.0
Ok to proceed? (y)

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.19 GB / 7.90 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.423.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.1
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
请提供复现

**Comment by DMzmwh** [comment]
[Uploading uni-shop.zip…]()

**Comment by ModyQyW** [comment]
如果你正在使用 pnpm，你应该设置 shamefully-hoist=true，参考 https://github.com/uni-helper/vitesse-uni-app/blob/main/.npmrc，同时你提交问题的时候不应该说你正在使用 npm 作为包管理器。

提交问题模板也说明了一个复现是必须的，大家的时间都很宝贵，谢谢。

**Comment by DMzmwh** [comment]
应该设置 shamefully-hoist=true，参考 https://github.com/uni-helper/vitesse-uni-app/blob/main/.npmrc

**Comment by DMzmwh** [comment]
多谢大佬
