### ISSUE TITLE
基于 Vitepress 的文档

### ISSUE THREAD

**Issue by Ares-Chang** [uni-helper/uni-network#44]
### 对问题的清晰和简明的描述

Hi,当前项目 README 文件过长，不利于阅读，是否有考虑过生成一个文档网站。

### 推荐的解决方案

我基于 Vitepress 生成了一个在线文档，[链接](https://cheery-liger-3c8a92.netlify.app/)。

![image](https://github.com/uni-helper/uni-network/assets/36911513/0d814d9e-700d-4dd7-9f74-ba8af4f5ae63)

项目是否需要，如果可以我会 PR 到当前仓库

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
欢迎PR！👏🏻

**Comment by Ares-Chang** [comment]
有个问题，这个链接挂到哪里，还是使用 netlify 部署的链接

**Comment by Ares-Chang** [comment]
更新至 #45 ，关闭此 Issues
