### ISSUE TITLE
支付宝响应cookies为undefined

### ISSUE THREAD

**Issue by serein-man** [uni-helper/uni-network#47]
### 描述问题

cookies没有值
最新版本

![image](https://github.com/uni-helper/uni-network/assets/26270639/196a7737-2d08-478a-aa9c-3b2f9bb4ead0)

微信小程序正常
![image](https://github.com/uni-helper/uni-network/assets/26270639/836ebec0-4edb-4f61-9ccb-88892c07dd23)

### 复现

1

### 系统信息

```Shell
1
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
请提供复现

**Comment by ModyQyW** [comment]
可以先尝试用 uni.request 看看有没有问题，如果有就不是 uni-network 的问题。
