### ISSUE TITLE
微信小程序平台：Rollup failed to resolve import "statuses" from "node_modules/@uni-helper/uni-network/dist/index.mjs"

### ISSUE THREAD

**Issue by kylsin** [uni-helper/uni-network#5]
### 描述问题

只要调用un的请求，在小程序平台就会弹出ru如下错误，编译不通过
![image](https://user-images.githubusercontent.com/32925530/209747205-f160eb1b-d43b-42fa-8b31-c4b57406b5ed.png)

### 复现

```
<template></template>

<script lang="ts" setup>
<script lang="ts" setup>
import un from '@uni-helper/uni-network'
un.get('http://t.weather.sojson.com/api/weather/city/101030100')
.then((res) => {
  console.log(res)
})
</script>
<style scoped lang="scss"></style>
```
![image](https://user-images.githubusercontent.com/32925530/209746680-c812d689-1405-4fa5-b13a-a922f3b9f67b.png)

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 13.14 GB / 31.93 GB
  Binaries:
    Node: 16.17.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - D:\nodejs\npm.CMD
  paltform:WeChat
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
我这里尝试了一下但无法复现，请提供一个 demo 链接。

我使用的 demo 地址是 https://github.com/MillCloud/presets/tree/main/uni-app。

效果图如下。可以正常发起请求。

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/209750563-6270dfdd-97a1-4b3f-9f19-40da3d4885c2.png">

**Comment by kylsin** [comment]
您好，demo仓库地址为 [https://github.com/kylsin/uni-app-demo](https://github.com/kylsin/uni-app-demo)
```
pnpm i
pnpm dev:mp-weixin
```

**Comment by ModyQyW** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/209754503-7de423e0-5fb7-48ec-8dac-2eccac151965.png">

我这边使用了你提供的 demo 还是不能复现出来。会不会是 node 和 pnpm 版本有影响？

```shell
➜  [/Users/wurui/Documents/uni-app-demo] git:(master) ✗ node -v              
v18.12.0
➜  [/Users/wurui/Documents/uni-app-demo] git:(master) ✗ pnpm -v               
7.20.0
```

**Comment by kylsin** [comment]
我已将node和pnpm升级
```
PS D:\study\uni-app-demo> node -v
v18.12.1
PS D:\study\uni-app-demo> pnpm -v
7.20.0
PS D:\study\uni-app-demo> npm -v
8.19.2
```
发现pnpm 安装依赖会出现此问题
![image](https://user-images.githubusercontent.com/32925530/209755695-eab166f7-f735-4dee-8194-e4087891c290.png)

npm安装依赖能正常通过
![image](https://user-images.githubusercontent.com/32925530/209755603-9b08fa5a-3d14-4199-aeb9-7b7ab784cd6a.png)

**Comment by ModyQyW** [comment]
奇怪的是我使用 pnpm 也是正常的。如果能让我这边也复现这个问题，我应该能更深入地看一下这个问题。

鉴于 uni-app 本身对 pnpm 支持较差，我倾向于认为这是 uni-app 和 pnpm 结合使用的问题。建议使用 npm 或者 yarn 来开发 uni-app 项目。

**Comment by kylsin** [comment]
好的，感谢
