### ISSUE TITLE
TypeError: Cannot assign to read only property 'constructor' of function 'function () 

### ISSUE THREAD

**Issue by xiaohe0601** [uni-helper/uni-network#50]
### Describe the bug

```shell
TypeError: Cannot assign to read only property 'constructor' of function 'function () { [native code] }'
    at forEach.allOwnKeys.allOwnKeys (@uni-helper_uni-network.js:1900:1)
    at forEach (@uni-helper_uni-network.js:1892:1)
    at extend (@uni-helper_uni-network.js:1897:1)
    at createInstance (@uni-helper_uni-network.js:2698:1)
    at @uni-helper_uni-network.js:2703:1
```

### Reproduction

`dev:h5`

https://github.com/uni-helper/uni-network/blob/c6e7a63088a38ae3ff8b131bc325e98a55f6b975/src/utils/extend.ts#L17

### System Info

基础环境信息:
  - os: `Windows 11 10.0.22631`
  - node: `20.13.1`
  - packageManager: `pnpm`
  - vscode: `1.91.0`
  - volar: `1.8.27`

基础依赖信息:
  - vue: `3.4.31`
  - vite: `5.3.3`
  - @dcloudio/uni-app: `3.0.0-alpha-4010920240607001`

uni-helper依赖信息:
  - @uni-helper/uni-network: `0.19.1`

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alva-lin** [comment]
我也出现这个问题了，试了下 `0.18.1` 版本还是可用的。

**Comment by ModyQyW** [comment]
请尝试一下 0.19.2

**Comment by xiaohe0601** [comment]
没问题了😀

**Comment by ModyQyW** [comment]
补充了 tests，见 https://github.com/uni-helper/uni-network/commit/6d4654131aec92788f874cd9bfe102b393d4b483，希望后续不会再出现这个问题。
