### ISSUE TITLE
alpha版本uniapp报错

### ISSUE THREAD

**Issue by YaWeiBoy** [uni-helper/uni-network#51]
### 描述问题

​node_modules/statuses/index.js (8:7): Error when using sourcemap for reporting an error: Can't resolve original location of error.​
11:45:35.120 node_modules/statuses/index.js (8:7): "default" is not exported by "
11:45:35.128 at ../node_modules/statuses/index.js:8:7
11:45:35.140    6:  */
11:45:35.152    7: import * as commonjsHelpers from "
11:45:35.160    8: import require$$0 from "\u0000D:/free/uniapp/uni-bug/node_modules/statuses/codes.json?commonjs-proxy";
11:45:35.174              ^
11:45:35.184    9: 
11:45:35.188   10: 'use strict'

### 复现

是cli方式创建uniapp项目 引用@uni-helper/uni-network

### 系统信息

create-uni@1.4.2

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by YaWeiBoy** [comment]
[uni-bug.zip](https://github.com/user-attachments/files/16607859/uni-bug.zip)
demo

**Comment by ModyQyW** [comment]
请找 uni-app 官方解决

**Comment by YaWeiBoy** [comment]
这个问题在最新版本3.0.0-4020820240925001出现了
