### ISSUE TITLE
有个依赖报错？？

### ISSUE THREAD

**Issue by gitwd1998** [uni-helper/uni-network#52]
### 描述问题

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/b9efa21a-b1bb-4544-abe4-07085476c30c">

### 复现

vite环境
<img width="643" alt="image" src="https://github.com/user-attachments/assets/495c444b-8535-4086-ba32-d4de00d1629a">
<img width="652" alt="image" src="https://github.com/user-attachments/assets/c8613096-5abf-41b1-aaff-4f95f3daa136">
<img width="522" alt="image" src="https://github.com/user-attachments/assets/34110345-8de4-4eef-9aa9-dc1ecc8b4d71">
<img width="763" alt="image" src="https://github.com/user-attachments/assets/2c1a9d11-57be-4dfc-bb5b-ba8860e02e09">

### 系统信息

<img width="810" alt="image" src="https://github.com/user-attachments/assets/95fdf9d6-cd11-4c5c-ad62-3d922d741e68">

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by wtto00** [comment]
没有复现到，麻烦提供一个最小复现项目

**Comment by gitwd1998** [comment]
[my-project.zip](https://github.com/user-attachments/files/16920949/my-project.zip)
![image](https://github.com/user-attachments/assets/b32328a1-5565-4890-bda7-19d7b4d37a28)
![image](https://github.com/user-attachments/assets/d1ea2847-b684-4ca7-aacf-d1aeec47157c)

**Comment by wtto00** [comment]
感谢回复，根据提供的资料，确实复现到了，初步猜测是uniapp的新版本有问题，版本号大于`40204`的就有问题。

1. 在项目中执行`pnpm build`
2. 然后更改`playground/package.json`中的`uniapp`版本
3. 之后使用命令`pnpm -C playground install && pnpm -C playground run dev:mp-weixin`
 
简单测试了几个版本，结果如下
|uniapp版本|对应的HBuilderX版本|结果|
|---|---|---|
|3.0.0-alpha-4020720240905001|4.27-alpha|❌|
|3.0.0-alpha-4020720240904001|4.27-alpha|❌|
|3.0.0-alpha-4020620240822002|4.26-alpha|❌|
|3.0.0-alpha-4020520240808001|4.25-alpha|❌|
|3.0.0-alpha-4020320240703001|4.23-alpha|✅|
|3.0.0-4020420240722002|4.24|✅|
|3.0.0-4020420240722001|4.24|✅|
|3.0.0-4020320240708001|4.23|✅|
|3.0.0-4010520240507001|4.15|✅|

@gitwd1998 可暂时使用最新的正式版本`3.0.0-4020420240722002`来解决此问题

**Comment by codeflyA** [comment]
同样遇到了 一样的问题 现在只能等uniapp官方修复？

**Comment by codeflyA** [comment]
3.0.0-alpha-4020720240913001  依然复现

**Comment by codeflyA** [comment]
可以将statuses请求库 替换为es module的库吗？ require慢慢vite支持不够好了

**Comment by wtto00** [comment]
@codeflyA 可以试试，据我所知，uniapp对es module支持不太好。欢迎PR。

**Comment by ModyQyW** [comment]
换成https://github.com/esm-ts/statuses-es？
